# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  ganache-cli = nodeEnv.buildNodePackage {
    name = "ganache-cli";
    packageName = "ganache-cli";
    version = "6.4.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/ganache-cli/-/ganache-cli-6.4.3.tgz";
      sha512 = "3G+CK4ojipDvxQHlpX8PjqaOMRWVcaLZZSW97Bv7fdcPTXQwkji2yY5CY6J12Atiub4M4aJc0va+q3HXeerbIA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "<p align=\"center\">   <em>NOTICE</em>: <code>testrpc</code> is now <code>ganache-cli</code>. Use it just as you would <code>testrpc</code>. </p> <hr/>";
      homepage = "https://github.com/trufflesuite/ganache-cli#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
}