ARG ALPINE_VERSION=edge

FROM alpine:${ALPINE_VERSION} as builder

ARG GANACHE_SUBDIR=./priv/presets/ganache-cli

RUN apk update && \
    apk add --no-cache make gcc g++ python git bash nodejs npm
COPY ${GANACHE_SUBDIR}/package.json /app/package.json
COPY ${GANACHE_SUBDIR}/package-lock.json /app/package-lock.json
WORKDIR /app
RUN npm install
COPY ${GANACHE_SUBDIR} .
RUN npx webpack-cli --config ./webpack/webpack.docker.config.js

# Release image
FROM alpine:${ALPINE_VERSION} as runtime

ENV VERSION=v10.14.1 \
    DOCKER=true

WORKDIR /app

COPY --from=builder "/app/node_modules/scrypt/build/Release" "./node_modules/scrypt/build/Release/"
COPY --from=builder "/app/node_modules/ganache-core/node_modules/scrypt/build/Release" "./node_modules/ganache-core/node_modules/scrypt/build/Release/"
COPY --from=builder "/app/node_modules/ganache-core/node_modules/secp256k1/build/Release" "./node_modules/ganache-core/node_modules/secp256k1/build/Release/"
COPY --from=builder "/app/node_modules/ganache-core/node_modules/keccak/build/Release" "./node_modules/ganache-core/node_modules/keccak/build/Release/"
COPY --from=builder "/app/node_modules/sha3/build/Release" "./node_modules/sha3/build/Release/"
COPY --from=builder "/app/node_modules/ganache-core/node_modules/websocket/build/Release" "./node_modules/ganache-core/node_modules/websocket/build/Release/"
COPY --from=builder "/app/build/ganache-core.docker.cli.js" "./ganache-core.docker.cli.js"
# COPY --from=builder "/app/build/ganache-core.docker.cli.js.map" "./ganache-core.docker.cli.js.map"

RUN apk add --no-cache nodejs geth && \
    ln -s /app/ganache-core.docker.cli.js /usr/bin/ganache-cli && \
    chmod 755 /usr/bin/ganache-cli

CMD ["ganache-cli"]